CREATE DATABASE TIENDA;
USE TIENDA;
SHOW DATABASES;

CREATE TABLE USER (
ID INT NOT NULL AUTO_INCREMENT,
NOMBRE VARCHAR(255) NOT NULL,
EDAD INT NOT NULL,
EMAIL VARCHAR(255) NOT NULL,
PRIMARY KEY(ID)
);

INSERT INTO USER (NOMBRE, EDAD, EMAIL)
VALUES
/*("TONI", 20, "toni@gmail.com"),
("JUAN", 30, "juan@gmail.com"),
("LUCAS", 40, "lucas@gmail.com"),
("CAROLINA", 50, "carolina@gmail.com");*/
("PEDRO",25,"pedro@gmail.com"),
("MARIA",51,"maria@gmail.com");

CREATE TABLE PRODUCTS (
ID INT NOT NULL AUTO_INCREMENT,
NOMBRE VARCHAR(50) NOT NULL,
CREATED_BY INT NOT NULL,
MARCA VARCHAR(50) NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY(CREATED_BY) REFERENCES USER(ID)
);

INSERT INTO PRODUCTS (NOMBRE, CREATED_BY, MARCA)
VALUES
/*("iPHONE 14", 1, "APPLE"),
("GALAXY", 1, "SAMSUNG"),
("REDMI NOTE", 2, "XIOMI"),
("LATTITUDE", 3, "DELL"),
("THINKPAD", 4, "LENOVO"),
("PROBOOK", 3, "HP");*/
("IPAD", 6,"APPLE");

SELECT * FROM USER;
SELECT * FROM PRODUCTS;
DELETE FROM PRODUCTS WHERE ID = 9;

SELECT PRODUCTS.NOMBRE, PRODUCTS.MARCA, USER.NOMBRE AS USUARIO
FROM PRODUCTS
LEFT JOIN USER 
ON PRODUCTS.CREATED_BY = USER.ID;

SELECT USER.NOMBRE, USER.EDAD, USER.EMAIL, PRODUCTS.NOMBRE AS ARTICULO, PRODUCTS.MARCA AS MARCA
FROM USER
LEFT JOIN PRODUCTS
ON USER.ID = PRODUCTS.CREATED_BY;

SELECT USER.NOMBRE, USER.EDAD, USER.EMAIL, PRODUCTS.NOMBRE AS ARTICULO, PRODUCTS.MARCA AS MARCA
FROM PRODUCTS
RIGHT JOIN USER 
ON PRODUCTS.CREATED_BY = USER.ID;

SELECT PRODUCTS.NOMBRE, PRODUCTS.MARCA, USER.NOMBRE AS USUARIO
FROM PRODUCTS
INNER JOIN USER 
ON PRODUCTS.CREATED_BY = USER.ID;

SELECT PRODUCTS.NOMBRE, PRODUCTS.MARCA, USER.NOMBRE AS USUARIO
FROM PRODUCTS
FULL OUTER JOIN USER 
ON PRODUCTS.CREATED_BY = USER.ID;